# Generated by Django 3.1.4 on 2020-12-19 20:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tabuleiro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tempo_ultima_jogada', models.DateField(verbose_name='Ultima Jogada')),
                ('casa1', models.IntegerField()),
                ('casa2', models.IntegerField()),
                ('casa3', models.IntegerField()),
                ('casa4', models.IntegerField()),
                ('casa5', models.IntegerField()),
                ('casa6', models.IntegerField()),
                ('casa7', models.IntegerField()),
                ('casa8', models.IntegerField()),
                ('casa9', models.IntegerField()),
                ('jogador1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jogador1', to=settings.AUTH_USER_MODEL)),
                ('jogador2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jogador2', to=settings.AUTH_USER_MODEL)),
                ('jogador_da_vez', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jogador_da_vez', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
