# Generated by Django 3.1.4 on 2020-12-20 23:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_auto_20201219_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabuleiro',
            name='jogador1',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(None), related_name='jogador1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tabuleiro',
            name='jogador2',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(None), related_name='jogador2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tabuleiro',
            name='jogador_da_vez',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(None), related_name='jogador_da_vez', to=settings.AUTH_USER_MODEL),
        ),
    ]
