# Generated by Django 3.1.4 on 2020-12-21 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201220_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabuleiro',
            name='tempo_ultima_jogada',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ultima Jogada'),
        ),
    ]
